name: deploy-website

on:
  push:
    branches: [master]

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.8.4"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'
      with:
        ref: ${{ github.head_ref }}
 
    - uses: actions/setup-haskell@v1.1.4
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Install dependencies
      run: |
        stack build --only-dependencies

    - name: Build
      run: |
        stack build

    - name: Exec
      run: |
        stack exec myblog clean
        stack exec myblog build
        
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "docs/CNAME"
        FILE_DATA: "richard-yu.ca"
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build and deploy site
        
